### ISSUE TITLE
India Topo json

### ISSUE THREAD

**Issue by nishadhka** [arundhaj/d3js_sandbox#1]
Hi,
Thank you very much for the code https://github.com/arundhaj/d3js_sandbox/blob/master/maps/maps.html, it helped me to learn D3 js visualization of India Topojson map. Please find this [topojson](https://github.com/nishadhka/riceWGI/blob/master/INDIA_TOPO.json) for a correct map of india, can be viewed ![as](https://github.com/nishadhka/riceWGI/blob/master/India_Topo.png?raw=true)

**Comment by arundhaj** [comment]
Hi,
Glad it had helped you. 
Thanks for letting me know, I'll try to update the map sometime.
